name       : brave
version    : 0.23.39
release    : 10
source     :
    - git|https://github.com/brave/browser-laptop: v0.23.39dev
license    :
    - MPL-2.0
    - GPL-3.0-or-later # Https Everywhere
    - GPL-2.0-or-later # Privacy Badger
component  : network.web.browser
summary    : A browser with your interests at heart.
description: |
    Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - nodejs
rundeps    :
    - libgnome-keyring
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-override-the-default-workspace-switching-short.patch
    npm install
    npm run postinstall
build      : |
    CHANNEL=dev npm run build-package
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/brave/
    cp -R brave-linux-x64/* $installdir/usr/share/brave/
    ln -s /usr/share/brave/brave $installdir/usr/bin/brave
    install -Dm0644 $pkgfiles/brave.desktop $installdir/usr/share/applications/brave.desktop
    install -Dm0644 res/dev/app.png $installdir/usr/share/pixmaps/brave.png
