name       : brave
version    : 1.11.101
release    : 69
source     :
    - https://github.com/brave/brave-browser/releases/download/v1.11.101/brave-browser_1.11.101_amd64.deb : d697673e63c4edcd34ed22f84c28422bbc1c8516339a900abd85f4addbddbc90
homepage   : https://brave.com
license    :
    - MPL-2.0
    - GPL-3.0-or-later # Https Everywhere
    - GPL-2.0-or-later # Privacy Badger
component  : network.web.browser
summary    : A browser with your interests at heart.
description: |
    Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
rundeps    :
    - libgnome-keyring
install    : |
    ar x $sources/brave-browser_${version}_amd64.deb
    tar xf data.tar.*
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/brave.com/brave $installdir/usr/share/
    ln -sfn /usr/share/brave/brave $installdir/usr/bin/brave-browser
    install -Dm0644 opt/brave.com/brave/product_logo_128.png $installdir/usr/share/pixmaps/brave-browser.png

    # Remove stuff that aren't necessary on Solus
    sed -i 's/brave-browser-stable/brave-browser/g' $installdir/usr/share/applications/brave-browser.desktop
    rm -f $installdir/usr/share/man/man1/brave-browser-stable.1.gz
    rm -f $installdir/usr/bin/brave-browser-stable
