name       : brave
version    : 1.24.84
release    : 80
source     :
    - https://github.com/brave/brave-browser/releases/download/v1.24.84/brave-browser_1.24.84_amd64.deb : 5fd4db82cec1c42e2a68c966e99d50ad276561363296104dbaf80ee1cbdcf027
homepage   : https://brave.com
license    :
    - MPL-2.0
    - GPL-3.0-or-later # Https Everywhere
    - GPL-2.0-or-later # Privacy Badger
component  : network.web.browser
summary    : A browser with your interests at heart.
description: |
    Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - cups-devel
rundeps    :
    - libgnome-keyring
setup      : |
    ar x $sources/brave-browser_${version}_amd64.deb
    tar xf data.tar.*
    mv usr/share/man/man1/brave-browser-stable.1.gz usr/share/man/man1/brave-browser.1.gz
install    : |
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/brave.com/brave $installdir/usr/share/
    ln -sfn /usr/share/brave/brave $installdir/usr/bin/brave-browser
    install -Dm00644 opt/brave.com/brave/product_logo_128.png $installdir/usr/share/pixmaps/brave-browser.png

    # Remove stuff that aren't necessary on Solus
    sed -i 's/brave-browser-stable/brave-browser/g' $installdir/usr/share/applications/brave-browser.desktop
    rm -f $installdir/usr/bin/brave-browser-stable
    rm -f $installdir/usr/share/brave/LICENSE
