name       : brave
version    : 0.59.34
release    : 18
source     :
    - https://github.com/brave/brave-browser/releases/download/v0.59.34/brave-browser_0.59.34_amd64.deb : 532b6b8b54a9274efcf36b030e7a7d1ea3d4d206e840c34580001f3402f024c4
homepage   : https://brave.com
license    :
    - MPL-2.0
    - GPL-3.0-or-later # Https Everywhere
    - GPL-2.0-or-later # Privacy Badger
component  : network.web.browser
summary    : A browser with your interests at heart.
description: |
    Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
rundeps    :
    - libgnome-keyring
install    : |
    ar x $sources/brave-browser_${version}_amd64.deb
    tar xf data.tar.*
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/brave.com/brave $installdir/usr/share/
    ln -sfn /usr/share/brave/brave $installdir/usr/bin/brave-browser
    install -Dm0644 opt/brave.com/brave/product_logo_128.png $installdir/usr/share/pixmaps/brave-browser.png
